name: CI
on:
- push
- pull_request
jobs:
  main:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
        - python: '3.6'
        - python: '3.7'
        - python: '3.8'
        - python: '3.9'
        - python: '3.10'
        - python: '3.11-dev'
    steps:
    - uses: actions/checkout@v2
    - name: set up Python ${{matrix.python}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python}}
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra -v tjmer
    - name: run pyflakes
      run: |
        python3 -m pip install pyflakes
        python3 -m pyflakes tjmer
    - name: run pylint
      run: |
        python3 -m pip install pylint
        python3 -m pylint tjmer
      if: matrix.python != '3.11-dev'
    - name: smoke test
      run: |
        ./tjmer --help
        ./tjmer 1s
        ./tjmer $(date +@%H:%M:%S -d '+1sec')
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
